baseURL = "https://nickolaskraus.org/"
languageCode = "en-us"
title = "Nickolas Kraus"
author = "Nickolas Kraus"
canonifyurls = true
theme = "black-and-light-2"

pygmentsStyle       = "tango"
pygmentscodefences  = true

[params]
  sitename = "Nickolas Kraus"
  dateFormat = "January 2, 2006"

[[menu.main]]
    name = "About"
    url  = "/about"
[[menu.main]]
    name = "Articles"
    url  = "/articles"
[[menu.main]]
    name = "Resume"
    url  = "/resume"
[[menu.main]]
    name = "The Good Parts"
    url  = "/the-good-parts"