baseURL = "https://nickolaskraus.org"
languageCode = "en-us"
title = "Nickolas Kraus"
author = "Nickolas Kraus"
canonifyurls = true
theme = "black-and-light-2"

pygmentsStyle       = "tango"
pygmentsCodeFences  = true

googleAnalytics = "UA-115911814-1"

[params]
  siteName = "Nickolas Kraus"
  dateFormat = "January 2, 2006"

[params.social]
  email = "nickhkraus@gmail.com"
  github = "https://github.com/NickolasHKraus"
  linkedin = "https://linkedin.com/in/nickolas-kraus"
  stackoverflow = "https://stackoverflow.com/users/9659079/nickolashkraus"
  twitter = "https://twitter.com/NickolasHKraus"

[[menu.main]]
    name = "About"
    url  = "/about"
[[menu.main]]
    name = "Articles"
    url  = "/articles"
[[menu.main]]
    name = "Resume"
    url  = "/resume.pdf"

[[menu.secondary]]
    name = "German"
    url  = "/german"
[[menu.secondary]]
    name = "Japanese"
    url  = "/japanese"
[[menu.secondary]]
    name = "Reading"
    url  = "/reading"
[[menu.secondary]]
    name = "Technology"
    url  = "/technology"
[[menu.secondary]]
    name = "Travel"
    url  = "/travel"
