baseURL = "https://nickolaskraus.io"
languageCode = "en-us"
title = "Nickolas Kraus"
author = "Nickolas Kraus"
canonifyurls = true
theme = "black-and-light-2"

pygmentsStyle       = "tango"
pygmentsCodeFences  = true

googleAnalytics = "UA-115911814-1"

[params]
  siteName = "Nickolas Kraus"
  dateFormat = "January 2, 2006"

[[menu.main]]
  name = "About"
  url  = "/about"
[[menu.main]]
  name = "Articles"
  url  = "/articles"
[[menu.main]]
  name = "Projects"
  url  = "/projects"
[[menu.main]]
  name = "Resume"
  url  = "/resume.pdf"
[[menu.main]]
  name = "Transcripts"
  url  = "/transcripts"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
