baseURL = 'https://nickolaskraus.io'
languageCode = 'en-us'
title = 'Nickolas Kraus'
theme = 'paperwhite'

[markup]
  [markup.highlight]
    # Disable syntax highlighting.
    noClasses = false

[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'

[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'
