baseURL = 'https://nickolaskraus.io'
languageCode = 'en-us'
title = 'Nickolas Kraus'
theme = 'black-and-light-2'

# Google Analytics measurement ID (Google Analytics 4)
[services]
  [services.googleAnalytics]
    id = 'G-F40Z5JD5FQ'

[markup]
  [markup.highlight]
  codeFences = true
  guessSyntax = false
  highlight = true
  # See: https://xyproto.github.io/splash/docs/
  # style = 'bw'
  # Uses a custum, external CSS file. See assets/scss/syntax.scss.
  noClasses = false
  [markup.goldmark]
    [markup.goldmark.extensions]
    taskList = false
    typographer = false
    [markup.goldmark.renderer]
    unsafe = true

[params]
  [params.about]
  title = 'Nickolas Kraus'
  description = 'Nickolas Kraus'

  [params.seo]
  meta_og_title = 'Nickolas Kraus'
  meta_og_description = 'Nickolas Kraus'
  meta_og_site_name = 'nickolaskraus.io'
  meta_og_image = 'logo.png'
  meta_twitter_title = 'Nickolas Kraus'
  meta_twitter_description = 'Nickolas Kraus'
  meta_twitter_site = '@nickolashkraus'
  meta_twitter_creator = '@nickolashkraus'
  meta_twitter_image = 'logo.png'

  [[params.socials]]
  name = 'Email'
  url = 'mailto:0x@nickolaskraus.io'

  [[params.socials]]
  name = 'Garmin'
  url = 'https://connect.garmin.com/modern/profile/6b22dde1-552e-45d4-9608-c5fe6b6d3ea4'

  [[params.socials]]
  name = 'GitHub'
  url = 'https://github.com/nickolashkraus'

  [[params.socials]]
  name = 'Instagram'
  url = 'https://www.instagram.com/nickolashkraus'

  [[params.socials]]
  name = 'LinkedIn'
  url = 'https://linkedin.com/in/nickolas-kraus'

  [[params.socials]]
  name = 'RSS'
  url = 'https://nickolaskraus.io/index.xml'

  [[params.socials]]
  name = 'Stack Overflow'
  url = 'https://stackoverflow.com/users/9659079/nickolashkraus'

  [[params.socials]]
  name = 'Strava'
  url = 'https://www.strava.com/athletes/23618436'

  [[params.socials]]
  name = 'X'
  url = 'https://x.com/nickolashkraus'

[[menus.main]]
name = 'About'
pageRef = '/about'
weight = 10

[[menus.main]]
name = 'Articles'
pageRef = '/articles'
weight = 20

[[menus.main]]
name = 'Projects'
pageRef = '/projects'
weight = 30

[[menus.main]]
name = 'Notes'
pageRef = '/notes'
weight = 40

[[menus.main]]
name = 'Resume'
pageRef = '/resume'
weight = 50

[[menus.main]]
name = 'Transcripts'
pageRef = '/transcripts'
weight = 60
